[tox]
envlist = py310, py311, py312, lint
isolated_build = True

[testenv]
deps = -r requirements-dev.txt
commands = pytest {posargs}

[testenv:lint]
deps =
    flake8
    mypy
    black
    isort
commands =
    flake8 src ui plugins
    black --check src ui plugins
    isort --check-only src ui plugins
